# meetsum configuration file
# Configuration values for the meeting summary generator

paths:
  # Base directory for customer meetings
  customers_dir: "/path/to/your/Customers/"

  # Directory containing the LLM instructions file
  automation_dir: "/path/to/your/automation/summaries"

  # LLM instructions file name
  instructions_file: "Meeting-summary-llm-instructions.md"

files:
  # Required files in meeting directory
  transcript: "transcript.txt"

  # Optional context files
  pov_input: "pov-input.md"

  # Output file naming pattern
  output_pattern: "{date}-{customer}-cadence-call-summary.md"

ai:
  # AI provider command to execute
  command: "gemini"

# Feature flags
features:
  # Enable trace mode by default
  trace_mode: false

  # Show file browser when no path provided
  file_browser: true

  # Enable markdown preview
  markdown_preview: true

# UI behavior
ui:
  # File browser settings
  file_browser:
    height: 15
    default_path: "/path/to/your/Customers/"

  # Input field settings
  input:
    name_placeholder: "Your Name"
    name_width: 30
    path_placeholder: "/path/to/Customers/[Customer]/[date]"
    path_width: 70